### ISSUE TITLE
Android Annotation on Polygon is causing havoc dismissing InfoWindow!

### ISSUE THREAD

**Issue by yozef** [appcelerator-modules/ti.map#119]
If we remove lines: 782 - 832 in TiUIMapView.java it would fix the issue. These lines breaks the annotation's default behaviour, and are a huge drain on performance for Android.

These lines are causing a lot of issues if there is a polygon underneath it. Basically it locks the UI thread for 6 seconds! Tested on an a Samsung S6 Edge.

I've tried All Day today to re-package this Module for Android, and I get a lot of errors trying to do so.
If anyone can help... 

On another note, is there an Order the the Libraries in Java Build Path?
<img width="450" alt="screen shot 2015-08-21 at 12 50 10 pm" src="https://cloud.githubusercontent.com/assets/287256/9413991/42bf71c8-4803-11e5-902d-455a18df1167.png">

For Some reason it's not finding: import com.google.android.gms.maps.model.*
Am I missing a .jar file?

**Comment by yozef** [comment]
For the life of me. I don't know why I can't package Ti.Map for Android?

I've packaged Modules before for Android, and developed one for iOS, but Ti.Map in particular for Android, is giving me issues.

I do foresee about 3 months left of committed work on this Module for an App, and would love if someone can help me figure out how to package my changes. I would like to contribute to this module.

**Comment by ashcoding** [comment]
For the changes you mentioned, is it possible to do a pull request for it with a sample app that shows the problem? That would be helpful in fixing the issue.

**Comment by yozef** [comment]
Hi @ashcoding you mean a Pull request for TiUIMapView.java or a Titanium App sample  that shows the problem?

**Comment by yozef** [comment]
I think this change should demonstrate what I was refering to: https://github.com/appcelerator-modules/ti.map/pull/120

**Comment by yozef** [comment]
Tried again today with this Pull request: https://github.com/appcelerator-modules/ti.map/pull/121

Travis still giving issues:
BUILD FAILED
/Users/travis/build/appcelerator-modules/ti.map/android/build.xml:9: Cannot find /module/android/build.xml imported from /Users/travis/build/appcelerator-modules/ti.map/android/build.xml

**Comment by ashcoding** [comment]
If you would like to build the module on your own, you could try this.

Checkout this version on Master
```bash
 git checkout 80f618536277d890f7e48e9db1a910c945d6fcdc
```
Modify: `ios/titanium.xcconfig` file to change sdk version to `TITANIUM_SDK_VERSION = 4.0.0.GA` or to a version that is available in your computer.

Have a `android\build.properties` file with information filled up. See `build.properties.example` for an example.

You can now compile the android version by going to the `android` folder and running the command `ant`.

For the iOS version, go to the `ios` folder and run `./build.py`

Hope that helps.

**Comment by yozef** [comment]
Hi @ashcoding Thanks for helping me out.

So I've deleted everything I've done, and restarted.
1- I've pulled the latest code from Github again.
2- Updated my Library with:
<img width="419" alt="screen shot 2015-08-24 at 7 51 49 am" src="https://cloud.githubusercontent.com/assets/287256/9439437/04025494-4a35-11e5-94b0-674ddd8bf146.png">
3- Now, there are no Errors in Studio
4- I create, and update build.properties to:
~~~
titanium.sdk=/Users/theFool/Library/Application\ Support/Titanium/
titanium.os=osx
titanium.version=4.1.0.GA
android.sdk=/Users/theFool/Library/android-sdk-macosx

titanium.platform=${titanium.sdk}/mobilesdk/${titanium.os}/${titanium.version}/android
android.platform=${android.sdk}/platforms/android-8
google.apis=${android.sdk}/add-ons/addon_google_apis_google_inc_8
~~~
5- I package the Module, then I get in the console:
~~~
Buildfile: /Users/xxx/Documents/Appcelerator_Studio_Workspace/titanium-map/build.xml

python.set.exec:

python.check:
        [echo] Testing for Python
        [exec] Python 2.7.6

init:

process.annotations:
       [javac] Compiling 13 source files to /Users/theFool/Documents/Appcelerator_Studio_Workspace/titanium-map/build/classes
       [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
       [javac] /Users/xxx/Documents/Appcelerator_Studio_Workspace/titanium-map/src/ti/map/AnnotationProxy.java:24: error: package android.graphics does not exist
       [javac] import android.graphics.Bitmap;
       [javac]                        ^
       [javac] /Users/xxx/Documents/Appcelerator_Studio_Workspace/titanium-map/src/ti/map/AnnotationProxy.java:25: error: package android.os does not exist
       [javac] import android.os.Message;
       [javac]                  ^
       [javac] /Users/xxx/Documents/Appcelerator_Studio_Workspace/titanium-map/src/ti/map/AnnotationProxy.java:26: error: package android.view does not exist
       [javac] import android.view.View;
~~~

**Comment by yozef** [comment]
Update:

I've updated my build.properties to match the version of the Android Library (18, used to be 8):
~~~
titanium.sdk=/Users/theFool/Library/Application\ Support/Titanium/
titanium.os=osx
titanium.version=4.1.0.GA
android.sdk=/Users/theFool/Library/android-sdk-macosx

titanium.platform=${titanium.sdk}/mobilesdk/${titanium.os}/${titanium.version}/android
android.platform=${android.sdk}/platforms/android-18 // To Match The Library version I added
google.apis=${android.sdk}/add-ons/addon_google_apis_google_inc_18 // To Match The Library version I added
~~~

Now when I package the Module, I get (**all good till the last 2 lines**):
~~~
python.set.exec:

python.check:
        [echo] Testing for Python
        [exec] Python 2.7.6

init:

process.annotations:

generate.v8.bindings:
        [java] Generating /Users/theFool/Documents/Appcelerator_Studio_Workspace/titanium-map/build/generated/jni/ti.map.CircleProxy.h
        **..... more of these for the different files**

generate.bindings:

pre.compile:

js.compile:

ndk.build:
        [copy] Copying 21 files to /var/folders/g0/p39677wx7m37r978qybw_69r0000gn/T/theFool/map-generated
        [exec] Android NDK: WARNING:jni/Android.mk:ti.map: non-system libraries in linker flags: -lkroll-v8    
        [exec] jni/Android.mk:35: warning: overriding commands for target `/private/var/folders/g0/p39677wx7m37r978qybw_69r0000gn/T/theFool/map-generated/KrollGeneratedBindings.cpp'
        [exec] Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    jni/Android.mk:35: warning: ignoring old commands for target `/private/var/folders/g0/p39677wx7m37r978qybw_69r0000gn/T/theFool/map-generated/KrollGeneratedBindings.cpp'
        [exec] Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    jni/Android.mk:38: warning: overriding commands for target `/private/var/folders/g0/p39677wx7m37r978qybw_69r0000gn/T/theFool/map-generated/BootstrapJS.cpp'
        [exec] Android NDK:     current module    
.... OK more of these...

check.build.arch:
        [echo] Architectures in manifest: armeabi armeabi-v7a x86
        [echo] Compiled binary architectures: armeabi;armeabi-v7a;x86

ndk.build.local:

compile:
       [javac] Compiling 1 source file to /Users/theFool/Documents/Appcelerator_Studio_Workspace/titanium-map/build/classes
       [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
       [javac] 1 warning
        [copy] Copying 1 file to /Users/theFool/Documents/Appcelerator_Studio_Workspace/titanium-map/build/classes

post.compile:

pre.dist:

dist:
         [jar] Building jar: /Users/theFool/Documents/Appcelerator_Studio_Workspace/titanium-map/dist/map.jar

post.jar:

python.set.exec:

python.check:
        [echo] Testing for Python
        [exec] Python 2.7.6

init:

pre.docgen:
docgen:
        [exec] Traceback (most recent call last):
        [exec] File "/Users/theFool/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/module/builder.py", line 255, in <module>
        [exec] main(sys.argv)
        [exec] File "/Users/theFool/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/module/builder.py", line 194, in main
        [exec] android_sdk = AndroidSDK(android_sdk_path)
        [exec] File "/Users/theFool/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/androidsdk.py", line 49, in __init__
        [exec] self.set_api_level(api_level)
        [exec] File "/Users/theFool/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/androidsdk.py", line 53, in set_api_level
        [exec] self.find_platform_dir()
        [exec] File "/Users/theFool/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/android/androidsdk.py", line 127, in find_platform_dir
        [exec] old_style_dir = os.path.join(self.android_sdk, 'platforms', android_api_levels[api_level])
        [exec] KeyError: 21

post.docgen:

check.respackage:

BUILD FAILED
/Users/theFool/Library/Application Support/Titanium/mobilesdk/osx/4.1.0.GA/module/android/build.xml:461: /Users/theFool/Documents/Appcelerator_Studio_Workspace/titanium-map/build/**docs does not exist.**
~~~

**Comment by yozef** [comment]
Done!! I created a /doc folder in /build and it Packaged successfully.

Hopefully this helps anybody else!

**Comment by yozef** [comment]
Update: So I've finally packaged my Module, I increased the version in the maniest file.

I add the Module to my App project, and I get this:
~~~
[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/LocationSource;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$4;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/StreetViewPanorama$OnStreetViewPanoramaChangeListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/StreetViewPanoramaFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$InfoWindowAdapter;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/MapsInitializer;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/MapFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$OnMyLocationButtonClickListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/UiSettings;
~~~

**Comment by yozef** [comment]
Can anybody that has the latest Ti.Map for Android running (and working in a apackaged state in the App), to drag a snapshot of their Java Build Path > Libraries please?

It would save me a lot of time. Thanks!

**Comment by yozef** [comment]
@ashcoding I've tried, many, many times I still get this issue when I use the packaged Ti.Map into my App:
~~~
[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/LocationSource;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$4;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/StreetViewPanorama$OnStreetViewPanoramaChangeListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/StreetViewPanoramaFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$InfoWindowAdapter;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/MapsInitializer;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/MapFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$OnMyLocationButtonClickListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/UiSettings;
~~~

**Comment by genocsb** [comment]
thanks it works
