### ISSUE TITLE
Error when using  the module

### ISSUE THREAD

**Issue by abada** [appcelerator-modules/ti.map#153]
```
ERROR] AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.salla.app/org.appcelerator.titanium.TiActivity}: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 7571000 but found 8487000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2626)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2706)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.access$800(ActivityThread.java:178)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
[ERROR] AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
[ERROR] AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6102)
[ERROR] AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
[ERROR] AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
[ERROR] AndroidRuntime: Caused by: java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 7571000 but found 8487000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
[ERROR] AndroidRuntime: 	at com.google.android.gms.common.GooglePlayServicesUtil.zzaa(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.maps.internal.zzy.zzaz(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.maps.internal.zzy.zzay(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.maps.SupportMapFragment$zzb.zzvu(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.maps.SupportMapFragment$zzb.zza(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
[ERROR] AndroidRuntime: 	at com.google.android.gms.maps.SupportMapFragment.onCreate(Unknown Source)
[ERROR] AndroidRuntime: 	at android.support.v4.app.Fragment.performCreate(Fragment.java:1939)
[ERROR] AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:988)
[ERROR] AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
[ERROR] AndroidRuntime: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
[ERROR] AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
[ERROR] AndroidRuntime: 	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
[ERROR] AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:511)
[ERROR] AndroidRuntime: 	at org.appcelerator.titanium.TiBaseActivity.onStart(TiBaseActivity.java:1291)
[ERROR] AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1295)
[ERROR] AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6131)
[ERROR] AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2583)
[ERROR] AndroidRuntime: 	... 10 more


```

**Comment by hansemannn** [comment]
Just read the error, that should solve it:
```
The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 7571000 but found 8487000.  You must have the following declaration within the <application> element:     
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
```
Thanks!

**Comment by abada** [comment]
Oh i noticed another module using different `gms.version` version  , i removed that version and changed it to  `@integer/google_play_services_version` and it works . thank you
