### ISSUE TITLE
Annotation with specific density image crashes on Android

### ISSUE THREAD

**Issue by AndreaVitale** [appcelerator-modules/ti.map#169]
I have some specific density image markers placed inside these folders:
```
/app/assets/android/res-hdpi
/app/assets/android/res-xhdpi
/app/assets/android/res-xxhdpi
/app/assets/android/res-xxxhdpi
```
when I use them to create an annotation my app crashes with this error:
```
[ERROR] TiApplication: (main) [698,2922] Sending event: exception on thread: main msg:java.lang.NullPointerException: IBitmapDescriptorFactory is not initialized; Titanium 5.3.0,2016/06/01 10:18,94fa8af
[ERROR] TiApplication: java.lang.NullPointerException: IBitmapDescriptorFactory is not initialized
[ERROR] TiApplication:     at com.google.android.gms.common.internal.zzu.zzb(Unknown Source)
[ERROR] TiApplication:     at com.google.android.gms.maps.model.BitmapDescriptorFactory.zzvH(Unknown Source)
[ERROR] TiApplication:     at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(Unknown Source)
[ERROR] TiApplication:     at ti.map.AnnotationProxy.handleImage(AnnotationProxy.java:235)
[ERROR] TiApplication:     at ti.map.AnnotationProxy.processOptions(AnnotationProxy.java:203)
[ERROR] TiApplication:     at ti.map.TiUIMapView.addAnnotation(TiUIMapView.java:403)
[ERROR] TiApplication:     at ti.map.TiUIMapView.addAnnotations(TiUIMapView.java:416)
[ERROR] TiApplication:     at ti.map.TiUIMapView.updateAnnotations(TiUIMapView.java:425)
[ERROR] TiApplication:     at ti.map.TiUIMapView.propertyChanged(TiUIMapView.java:266)
[ERROR] TiApplication:     at org.appcelerator.kroll.KrollPropertyChange.fireEvent(KrollPropertyChange.java:21)
[ERROR] TiApplication:     at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1093)
[ERROR] TiApplication:     at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:356)
[ERROR] TiApplication:     at ti.map.ViewProxy.handleMessage(ViewProxy.java:249)
[ERROR] TiApplication:     at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] TiApplication:     at android.os.Looper.loop(Looper.java:136)
[ERROR] TiApplication:     at android.app.ActivityThread.main(ActivityThread.java:5001)
[ERROR] TiApplication:     at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] TiApplication:     at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] TiApplication:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[ERROR] TiApplication:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[ERROR] TiApplication:     at dalvik.system.NativeStart.main(Native Method)
```

I also tried to check if the specific image exists before setting it as a marker image using this code:
```
                Ti.API.info("Setting marker to", marker);
                Ti.API.info("File exists?", Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, marker).exists());
```
and the output is
```
[INFO]  Setting marker to /images/private-available.png
[INFO]  File exists? true
[INFO]  Setting marker to /images/open-available.png
[INFO]  File exists? true
[INFO]  Setting marker to /images/private-available.png
[INFO]  File exists? true
```

**Comment by hansemannn** [comment]
Hey there,

can you file a [JIRA ticket](http://jira.appcelerator.org) for this issue? Thanks!

**Comment by yozef** [comment]
Odd... (Android) specific density image annotations (each within their folders) works for me.
IBitmapDescriptorFactory is not initialized seems like something else is going on. 
Maybe, try to make sure the Map is already loaded before adding annotations.

**Comment by AndreaVitale** [comment]
@yozef would be great only if "complete" event will be fired.

I have tried with:

```
$.Map.addEventListener("complete", completeHandler = function(event) {
    $.Map.removeEventListener("complete", completeHandler);

    Ti.API.info("Completed");
});
```

but the "Completed" log is never shown.

**Comment by yozef** [comment]
It does fire for me (almost similar code). 
~~~
function mapViewCompletedRendering() {
    Ti.API.info('******** mapview Complete Rendering ********');
    $.mapView.removeEventListener('complete', mapViewCompletedRendering);
};
$.mapView.addEventListener('complete', mapViewCompletedRendering);
~~~
When the The Map's tiles in visible view gets loaded, it fires the `complete` event; 
This gets fired also (unless you  remove the event listener) when you Pan the map to new tiles to be loaded.

I count on this event to display other information after the map is rendered its tiles/`complete`.

**Comment by hansemannn** [comment]
You need to place them in `/app/assets/android/images/res-hdpi` etc. If further discussion is required, please file a JIRA ticket for it, thanks!
